chore: protect against publishing alpha versions

diff --git a/.github/workflows/manual-publish.yml b/.github/workflows/manual-publish.yml
--- a/.github/workflows/manual-publish.yml
+++ b/.github/workflows/manual-publish.yml
@@ -31,6 +31,30 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ inputs.ref }}
+
+      - name: Get Package Version
+        id: version
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const manifest = JSON.parse(fs.readFileSync('package.json', 'utf8'));
+            const version = manifest.version;
+            core.setOutput('version', version);
+
+      - name: Display Info
+        uses: streetsidesoftware/actions/public/output@v1
+        with:
+          value: |
+            # Package Version
+            ref: ${{ inputs.ref }}
+            version: `${{ steps.version.outputs.version }}`
+
+      - name: Test Exit
+        run: |
+          echo "::error title=Test::This is a test error"
+          exit 1
+
       - name: Install
         run: |
           npm install
