ci: Update manual-publish.yml

diff --git a/.github/workflows/manual-publish.yml b/.github/workflows/manual-publish.yml
--- a/.github/workflows/manual-publish.yml
+++ b/.github/workflows/manual-publish.yml
@@ -28,7 +28,7 @@ jobs:
       - name: Build Extension .vsix
         run: yarn run package-extension
       - name: Publish VSCE
-        run: find ./build -name "*.vsix" | xargs npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath || echo skipped
+        run: find ./build -name "*.vsix" | xargs npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath || echo "::warning title=VSCE::Failed to Publish to VS Code Marketplace."
       - name: Publish OVSX
-        run: find ./build -name "*.vsix" | xargs npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}  || echo skipped
+        run: find ./build -name "*.vsix" | xargs npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}  || echo "::warning title=OVSX::Failed to Publish to Eclipse Open VSX."
 # cspell:ignore vsix xargs OVSX
