chore: protect against publishing alpha versions (#3049)

diff --git a/.github/workflows/manual-publish.yml b/.github/workflows/manual-publish.yml
--- a/.github/workflows/manual-publish.yml
+++ b/.github/workflows/manual-publish.yml
@@ -24,13 +24,68 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  publish:
+  check_version:
     runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.version.outputs.version }}
+      alpha: ${{ steps.version.outputs.alpha }}
+      validVersion: ${{ steps.version.outputs.validVersion }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           ref: ${{ inputs.ref }}
+
+      - name: Check Package Version
+        id: version
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const manifest = JSON.parse(fs.readFileSync('package.json', 'utf8'));
+            const version = manifest.version;
+            core.setOutput('version', version);
+            const alpha = version.includes('alpha');
+            core.setOutput('alpha', alpha || '');
+            const validVersion = /^\d+\.\d+\.\d+$/.test(version);
+            core.setOutput('validVersion', validVersion || '');
+            return {
+              version,
+              alpha,
+              validVersion
+            };
+
+      - name: Display Info
+        uses: streetsidesoftware/actions/public/summary@v1
+        with:
+          text: |
+            # Package Info
+            ref: ${{ inputs.ref }}
+            version: `${{ steps.version.outputs.version }}`
+            alpha: ${{ contains(steps.version.outputs.version, 'alpha') }}
+            validVersion: ${{ steps.version.outputs.validVersion }}
+            versionInfo: ${{ toJSON(steps.version.outputs) }}
+
+      - name: Check Version
+        if: ${{ steps.version.outputs.validVersion != 'true' }}
+        run: |
+          echo "::warning title=Do NOT Publish::The version in package.json is not a releasable version."
+
+  publish:
+    runs-on: ubuntu-latest
+    needs: check_version
+    if: ${{ needs.check_version.outputs.validVersion == 'true' }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.ref }}
+
+      - name: Test Exit
+        run: |
+          echo "::error title=Test::This is a test error"
+          exit 1
+
       - name: Install
         run: |
           npm install
