ci: fix false error logging in pub step.

diff --git a/.github/workflows/manual-publish.yml b/.github/workflows/manual-publish.yml
--- a/.github/workflows/manual-publish.yml
+++ b/.github/workflows/manual-publish.yml
@@ -30,12 +30,18 @@ jobs:
       - name: Publish VSCE
         run: >
           find ./build -name "*.vsix" | xargs npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath
-          || echo "PUB_FAIL=true" >> $GITHUB_ENV && echo "::error title=VSCE::Failed to Publish to VS Code Marketplace."
+          || echo "PUB_FAIL_VSCE=true" >> $GITHUB_ENV
+      - name: Check Publish Result VSCE
+        if: ${{ env.PUB_FAIL_VSCE }}
+        run: echo "::error title=VSCE::Failed to Publish to VS Code Marketplace."
       - name: Publish OVSX
         run: >
           find ./build -name "*.vsix" | xargs npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}
-          || echo "PUB_FAIL=true" >> $GITHUB_ENV && echo "::error title=OVSX::Failed to Publish to Eclipse Open VSX."
+          || echo "PUB_FAIL_OVSX=true" >> $GITHUB_ENV
+      - name: Check Publish Result OVSX
+        if: ${{ env.PUB_FAIL_OVSX }}
+        run: echo "::error title=OVSX::Failed to Publish to Eclipse Open VSX."
       - name: Check Build
-        if: ${{ env.PUB_FAIL }}
+        if: ${{ env.PUB_FAIL_VSCE || env.PUB_FAIL_OVSX }}
         run: exit 1
 # cspell:ignore vsix xargs OVSX
